---
framework: jasmine
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
postMerge:
  pattern:
    - "./i18n/spec/*.js"
    - "./i18n/ucd/spec/*.js"
# postRun:
#      command:
#         - yarn --version
nodeVersion: 14.16.1
# parallelism: 5
